# Generated by Django 3.0.6 on 2020-06-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakerall', '0002_auto_20200530_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
