# Generated by Django 3.0.6 on 2020-06-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakerall', '0003_auto_20200604_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MakeAnOrder',
        ),
    ]
