# Generated by Django 3.0.6 on 2020-06-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakerall', '0006_auto_20200608_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='composition_en',
            field=models.TextField(null=True, verbose_name='Состав выпечки'),
        ),
        migrations.AddField(
            model_name='food',
            name='composition_ru',
            field=models.TextField(null=True, verbose_name='Состав выпечки'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание выпечки'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание выпечки'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Название выпечки'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Название выпечки'),
        ),
    ]
